CREATE TABLE Cliente (
    id_cliente INT PRIMARY KEY,
    nombre VARCHAR(100),
    edad INT,
    genero VARCHAR(10),
    region VARCHAR(50),
    fecha_registro DATE,
    correo_electronico VARCHAR(100)
);

INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (1, 'Benito Llorens', 58, 'Masculino', 'Centro', '2024-03-13', 'xportero@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (2, 'Corona Molins Gálvez', 65, 'Femenino', 'Oriente', '2024-10-07', 'rubiopascual@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (3, 'Marcial Santamaría Torrent', 32, 'Masculino', 'Occidente', '2021-08-28', 'eugenia47@nevado-andres.org');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (4, 'Azahara Perelló Águila', 61, 'Femenino', 'Centro', '2021-04-16', 'elisabet70@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (5, 'Isidro Parejo-Casal', 20, 'Masculino', 'Centro', '2023-12-18', 'lupe59@tenorio.net');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (6, 'Guadalupe Arias Mateo', 31, 'Masculino', 'Occidente', '2024-10-25', 'bgranados@camacho.org');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (7, 'Visitación Vega Arranz', 53, 'Masculino', 'Occidente', '2024-07-27', 'kcisneros@pomares-infante.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (8, 'Dorita Toledo Bernad', 32, 'Femenino', 'Paracentral', '2021-06-27', 'luz58@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (9, 'Hipólito Sanchez Ibañez', 69, 'Masculino', 'Centro', '2023-02-07', 'virginiainiguez@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (10, 'Delfina Trujillo Roman', 62, 'Femenino', 'Paracentral', '2023-10-08', 'whoyos@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (11, 'Paula Borrell Cardona', 35, 'Femenino', 'Occidente', '2022-10-12', 'pcervera@mir-huerta.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (12, 'Jafet Zamora Adadia', 66, 'Masculino', 'Oriente', '2021-12-16', 'landafortunato@blanco-porcel.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (13, 'Urbano Silva Sanjuan', 23, 'Masculino', 'Paracentral', '2023-01-14', 'cpinedo@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (14, 'Dan Cabello Novoa', 40, 'Masculino', 'Oriente', '2023-10-07', 'lope72@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (15, 'Iker Escudero Martí', 69, 'Masculino', 'Centro', '2023-02-18', 'jredondo@salas.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (16, 'Dionisio Gálvez Raya', 52, 'Masculino', 'Centro', '2020-08-16', 'nalegria@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (17, 'Ariel Ortiz Grande', 23, 'Masculino', 'Oriente', '2024-02-24', 'emiliana02@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (18, 'Lisandro Río Mateo', 54, 'Masculino', 'Occidente', '2024-11-27', 'hilda21@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (19, 'Susanita Milla-Sales', 20, 'Femenino', 'Occidente', '2025-02-15', 'bernardino39@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (20, 'Danilo Casanova Anguita', 23, 'Masculino', 'Occidente', '2025-04-19', 'lupitamateo@dieguez.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (21, 'Vidal Jimenez Pablo', 42, 'Masculino', 'Oriente', '2022-05-10', 'omarti@puga.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (22, 'Maximiano Doménech-Alfonso', 58, 'Masculino', 'Oriente', '2021-05-04', 'umoran@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (23, 'Oriana Paredes Mármol', 41, 'Femenino', 'Oriente', '2020-10-29', 'dacedo@barbera.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (24, 'María Bermejo Salas', 60, 'Femenino', 'Oriente', '2023-08-20', 'claverojuan-luis@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (25, 'Odalys Barral Exposito', 56, 'Masculino', 'Occidente', '2022-05-10', 'bsolana@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (26, 'Graciela Castillo Valle', 28, 'Femenino', 'Paracentral', '2023-05-28', 'gonzalomarques@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (27, 'Samu de Ferrán', 35, 'Masculino', 'Occidente', '2022-12-02', 'mariselarocha@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (28, 'Edelmiro Beltran Roldán', 67, 'Masculino', 'Centro', '2023-04-01', 'brecio@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (29, 'Armando Puig Cabello', 70, 'Masculino', 'Centro', '2021-03-13', 'rherrera@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (30, 'Angélica Mendoza Elorza', 43, 'Femenino', 'Oriente', '2024-09-18', 'freina@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (31, 'David Pozuelo Madrigal', 31, 'Masculino', 'Oriente', '2022-05-01', 'alcantaracristian@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (32, 'Teobaldo Dani Rivera Sáez', 59, 'Masculino', 'Paracentral', '2020-07-22', 'nelida70@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (33, 'Ciro Molins-Donaire', 59, 'Masculino', 'Paracentral', '2023-02-01', 'graciajesusa@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (34, 'Eric Cornelio Barberá Sevillano', 34, 'Masculino', 'Occidente', '2021-12-22', 'naranjoarmida@escobar-gordillo.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (35, 'Marita Lladó Jerez', 65, 'Femenino', 'Oriente', '2020-06-24', 'fabregasvictor@luna-giron.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (36, 'Vito Revilla Silva', 55, 'Masculino', 'Paracentral', '2022-06-16', 'jerezroman@portillo-rios.org');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (37, 'Jose Solera-Alcázar', 32, 'Masculino', 'Occidente', '2024-11-02', 'mauraguzman@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (38, 'Liliana Casals', 23, 'Femenino', 'Centro', '2021-05-12', 'belenvazquez@pinilla-cerdan.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (39, 'Carlos de Casanova', 27, 'Masculino', 'Occidente', '2021-06-24', 'maximoalemany@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (40, 'Heraclio Pascual Sans Saldaña', 56, 'Masculino', 'Centro', '2023-01-29', 'cosmeiborra@elorza.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (41, 'Ámbar Prat-Arnaiz', 42, 'Masculino', 'Paracentral', '2021-02-20', 'maria-manuela42@nunez-tena.org');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (42, 'Dolores Perales Diéguez', 53, 'Masculino', 'Centro', '2023-07-03', 'roliveras@mulet.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (43, 'Noa Salmerón Castejón', 61, 'Femenino', 'Oriente', '2023-08-22', 'sordonez@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (44, 'Azahar Pont Llobet', 25, 'Masculino', 'Oriente', '2021-06-07', 'gustavo44@tejedor.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (45, 'Teo Esparza-Barranco', 28, 'Masculino', 'Paracentral', '2022-09-02', 'ugarate@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (46, 'Modesto Durán-Crespi', 64, 'Masculino', 'Oriente', '2025-02-24', 'francisco-javier62@exposito.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (47, 'Victorino del Chaves', 50, 'Masculino', 'Centro', '2020-09-01', 'lunarebollo@jaume.org');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (48, 'Conrado Segovia Calzada', 58, 'Masculino', 'Occidente', '2021-03-30', 'caldavid@aviles.org');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (49, 'Javi Aroca Benavente', 41, 'Masculino', 'Occidente', '2020-06-16', 'ucaballero@ayuso-gutierrez.org');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (50, 'Leocadio Lago-Atienza', 56, 'Masculino', 'Oriente', '2022-01-27', 'hugo08@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (51, 'Cloe Portillo Grande', 19, 'Masculino', 'Centro', '2022-07-15', 'guijarrofabiana@bermudez.net');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (52, 'Alonso de Coello', 69, 'Masculino', 'Oriente', '2021-12-04', 'miguelacarbajo@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (53, 'Teófilo Tovar Parejo', 21, 'Masculino', 'Occidente', '2020-11-25', 'wortega@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (54, 'Hernando Iñiguez Porcel', 23, 'Masculino', 'Paracentral', '2024-12-11', 'martirio77@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (55, 'Jimena Noa Azcona Tomé', 66, 'Femenino', 'Occidente', '2021-10-16', 'jeronimomena@castell-leon.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (56, 'Leyre Dominguez-Doménech', 60, 'Masculino', 'Paracentral', '2023-07-14', 'monicaandres@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (57, 'Sabina Cabezas Peñas', 34, 'Femenino', 'Paracentral', '2025-03-09', 'ytena@andrade.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (58, 'Sancho Palomo Frías', 52, 'Masculino', 'Occidente', '2024-03-15', 'corominasamelia@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (59, 'Fernando Alvarez Manrique', 43, 'Masculino', 'Oriente', '2021-12-07', 'noemifiguerola@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (60, 'Ulises Ricart Bou', 51, 'Masculino', 'Paracentral', '2023-11-09', 'dorotea79@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (61, 'Purificación Campos Velasco', 33, 'Masculino', 'Occidente', '2020-08-23', 'vidalestrada@llorens.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (62, 'Víctor del Osorio', 39, 'Masculino', 'Centro', '2023-05-06', 'mazaalicia@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (63, 'María Dolores Balaguer Cantero', 55, 'Femenino', 'Occidente', '2020-09-16', 'bienvenidagomila@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (64, 'Carmelita Duarte Sureda', 22, 'Femenino', 'Centro', '2021-03-15', 'moyatomas@alegria-luis.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (65, 'Anastasio Tena', 22, 'Masculino', 'Centro', '2023-07-31', 'zbueno@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (66, 'Jose Ramón Alarcón Azcona', 22, 'Masculino', 'Occidente', '2021-10-22', 'zgual@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (67, 'Graciana Pozo-Flores', 60, 'Femenino', 'Paracentral', '2022-09-06', 'pomaresmarcio@quiros.net');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (68, 'Ana Abad Giner', 52, 'Femenino', 'Occidente', '2022-03-17', 'federicopoza@teruel.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (69, 'Cristian Adelardo Jurado Criado', 33, 'Masculino', 'Paracentral', '2023-03-26', 'nelida81@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (70, 'Faustino José Ángel Oliveras Cañete', 30, 'Masculino', 'Centro', '2022-12-03', 'ralegria@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (71, 'Yago Lloret Reguera', 60, 'Masculino', 'Paracentral', '2024-11-17', 'edelmira11@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (72, 'Lisandro Arranz Feijoo', 45, 'Masculino', 'Paracentral', '2021-04-12', 'zhervas@bosch-nadal.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (73, 'Dorita Concepción Ugarte Palomares', 64, 'Femenino', 'Centro', '2022-02-03', 'faustino14@baron.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (74, 'Urbano Carmelo Zapata Amor', 21, 'Masculino', 'Paracentral', '2021-12-19', 'wcompany@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (75, 'Fulgencio Jara Llabrés', 69, 'Masculino', 'Centro', '2022-12-18', 'mariscalsandalio@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (76, 'Ezequiel Fábregas Rico', 30, 'Masculino', 'Occidente', '2020-12-21', 'jose-miguelbas@pastor.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (77, 'Blanca Corbacho Manzanares', 26, 'Femenino', 'Paracentral', '2022-11-20', 'ponciosalmeron@agusti-baron.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (78, 'Mirta Fernandez Cervera', 35, 'Femenino', 'Paracentral', '2021-02-25', 'ascension87@figueras.net');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (79, 'Áurea Montoya Perera', 22, 'Femenino', 'Paracentral', '2021-03-26', 'rosalesciriaco@pineda.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (80, 'Marianela Lerma Amo', 21, 'Femenino', 'Centro', '2021-02-02', 'parejaalma@llobet-espejo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (81, 'Zoraida Castilla Castañeda', 66, 'Femenino', 'Occidente', '2021-08-26', 'ftorres@alcantara.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (82, 'Prudencio Castañeda Mena', 44, 'Masculino', 'Paracentral', '2023-05-25', 'ramonanicolau@falco.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (83, 'Sara Vidal Bertrán', 31, 'Femenino', 'Paracentral', '2023-11-25', 'naranjoherberto@estrada.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (84, 'Clotilde de Carvajal', 28, 'Masculino', 'Paracentral', '2020-09-26', 'jmontenegro@zabaleta.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (85, 'Alejandra Salvador Pozo', 42, 'Femenino', 'Oriente', '2025-04-24', 'ana-sofia77@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (86, 'Teresita del Solsona', 36, 'Femenino', 'Paracentral', '2020-09-01', 'encarnitahernandez@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (87, 'Anita Adán Calvet', 27, 'Femenino', 'Occidente', '2020-10-12', 'malolilia@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (88, 'Amaro Cabo Donoso', 31, 'Masculino', 'Centro', '2020-06-08', 'arandaeusebia@moreno.org');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (89, 'Jose Roldán Barriga Caro', 65, 'Masculino', 'Oriente', '2021-11-10', 'verajosep@alamo.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (90, 'Nicolás Manzano', 21, 'Masculino', 'Paracentral', '2024-09-30', 'sanjuanchus@mata-neira.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (91, 'Nidia Porcel-Losada', 21, 'Femenino', 'Centro', '2022-08-17', 'nicanorbolanos@quintero.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (92, 'Cruz Agudo Berrocal', 22, 'Masculino', 'Centro', '2022-08-05', 'tlerma@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (93, 'Aurora Perea Tejero', 43, 'Femenino', 'Centro', '2023-01-05', 'xvives@cordero-pinol.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (94, 'Guiomar Guerrero Borja', 55, 'Masculino', 'Centro', '2020-10-04', 'pellicernereida@arnal-espinosa.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (95, 'Marc Torrent Acedo', 44, 'Masculino', 'Oriente', '2021-06-01', 'xminguez@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (96, 'Eligia Amaya Carmona Valbuena', 31, 'Femenino', 'Oriente', '2021-03-28', 'zmir@chaves.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (97, 'Socorro Ariza Mármol', 34, 'Masculino', 'Paracentral', '2024-07-10', 'josueplana@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (98, 'Chita Figuerola-Vila', 60, 'Femenino', 'Oriente', '2021-04-17', 'albasaura@riquelme.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (99, 'Albina Vilalta Ibarra', 38, 'Femenino', 'Centro', '2024-06-22', 'regina45@colomer.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (100, 'Serafina Bernad Farré', 47, 'Femenino', 'Centro', '2022-02-05', 'rebolloleire@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (101, 'Eugenio Paz Alarcón', 52, 'Masculino', 'Occidente', '2023-04-30', 'raquelfajardo@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (102, 'Santos del Chacón', 26, 'Masculino', 'Oriente', '2021-08-01', 'jacuna@barriga.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (103, 'Sebastian Barragán Durán', 33, 'Masculino', 'Oriente', '2024-02-14', 'candelasmercader@rubio.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (104, 'Adelina Catalán', 28, 'Femenino', 'Paracentral', '2020-11-12', 'kroldan@sanabria.org');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (105, 'María Manuela Lasa', 57, 'Femenino', 'Centro', '2021-09-22', 'juan-antonio67@buendia.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (106, 'Elba de Solís', 60, 'Femenino', 'Centro', '2023-11-22', 'qgodoy@prieto.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (107, 'Inocencio del Pedrero', 34, 'Masculino', 'Centro', '2021-03-31', 'montserrat34@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (108, 'Edelmira Crespi-Armengol', 65, 'Femenino', 'Occidente', '2023-05-22', 'rgomez@novoa.net');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (109, 'Gervasio Portero Escobar', 36, 'Masculino', 'Occidente', '2022-09-19', 'graciaencarnacion@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (110, 'Adelia Fabra Casanova', 31, 'Femenino', 'Oriente', '2022-04-17', 'gaston38@valbuena-roldan.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (111, 'Violeta Jurado Méndez', 34, 'Femenino', 'Centro', '2024-05-23', 'fulgencio39@arevalo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (112, 'Jose Ignacio Puerta Vazquez', 58, 'Masculino', 'Paracentral', '2022-07-01', 'martinezbibiana@bertran-lopez.net');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (113, 'Macaria Violeta Casares Álamo', 20, 'Femenino', 'Centro', '2024-08-12', 'omoya@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (114, 'Ángel Heredia Farré', 67, 'Masculino', 'Occidente', '2021-12-27', 'feliciano91@olivera-castellanos.net');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (115, 'Ignacio Lago Bayón', 28, 'Masculino', 'Paracentral', '2021-02-02', 'francisco-joseflores@valle.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (116, 'Luisa Diaz-Bartolomé', 53, 'Femenino', 'Centro', '2023-10-18', 'torralbacalixta@pablo.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (117, 'Joan Villalobos Valbuena', 22, 'Masculino', 'Occidente', '2024-12-10', 'dimas88@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (118, 'Juan José Velázquez-Capdevila', 41, 'Masculino', 'Occidente', '2022-07-10', 'olivia34@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (119, 'Salomón Varela', 26, 'Masculino', 'Centro', '2021-10-09', 'balduino81@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (120, 'Clímaco Mosquera-Cerro', 41, 'Masculino', 'Centro', '2023-12-20', 'hlastra@rico.net');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (121, 'María Teresa Rebollo', 31, 'Femenino', 'Occidente', '2023-11-24', 'agustingertrudis@blazquez.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (122, 'José Sanjuan Jaume', 40, 'Masculino', 'Paracentral', '2021-12-17', 'evaristohurtado@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (123, 'Agustín Lluch Ruiz', 33, 'Masculino', 'Occidente', '2022-07-22', 'arnaiznicodemo@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (124, 'Esmeralda Lobato Meléndez', 44, 'Femenino', 'Centro', '2023-10-03', 'gcanton@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (125, 'Cosme Barrio Calatayud', 65, 'Masculino', 'Oriente', '2024-09-14', 'leivapatricia@torrent-guerra.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (126, 'Isaura Seguí Moraleda', 69, 'Femenino', 'Occidente', '2020-06-25', 'palaudan@bastida.org');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (127, 'Pascuala Llopis Sola', 28, 'Femenino', 'Centro', '2022-09-11', 'qcamps@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (128, 'Santiago Barreda Manrique', 20, 'Masculino', 'Paracentral', '2021-11-14', 'pacogarcia@tejero-roma.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (129, 'Édgar Suarez Pozo', 30, 'Masculino', 'Paracentral', '2021-06-07', 'oteromaura@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (130, 'Estela Pagès Alvarez', 37, 'Femenino', 'Occidente', '2021-05-17', 'emilianacortes@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (131, 'Florina Abad-Cabrero', 19, 'Femenino', 'Occidente', '2024-01-23', 'infantenazaret@pla.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (132, 'Candela Echeverría Tur', 39, 'Femenino', 'Oriente', '2024-07-17', 'seguimaximo@fonseca-mora.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (133, 'Manu Murcia', 67, 'Masculino', 'Oriente', '2023-05-20', 'pallarestrinidad@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (134, 'Atilio Artigas-Valenzuela', 59, 'Masculino', 'Paracentral', '2022-03-11', 'osoriano@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (135, 'Victoria Dolores Zaragoza Herranz', 19, 'Femenino', 'Centro', '2023-09-13', 'andres-felipeguijarro@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (136, 'Priscila Chico Pinedo', 29, 'Femenino', 'Oriente', '2024-12-05', 'alicia49@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (137, 'Edu Mateo Gárate', 24, 'Masculino', 'Paracentral', '2023-10-01', 'pardoangelita@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (138, 'Eladio Calvo Guillén', 64, 'Masculino', 'Oriente', '2022-02-03', 'uramirez@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (139, 'Adolfo Ribes-Zamorano', 56, 'Masculino', 'Centro', '2024-05-21', 'maximianopombo@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (140, 'Remedios Sarabia Romero', 54, 'Masculino', 'Occidente', '2024-10-20', 'felicidad65@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (141, 'Loida Pombo-Canals', 20, 'Femenino', 'Paracentral', '2023-06-25', 'maciascelestina@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (142, 'Juan Bautista Ferrández', 51, 'Masculino', 'Occidente', '2022-12-17', 'smoran@anaya-huerta.net');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (143, 'Hugo Vicens Solera', 45, 'Masculino', 'Centro', '2023-06-16', 'tejadalisandro@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (144, 'Marcelino Serra Belda', 57, 'Masculino', 'Oriente', '2020-06-13', 'fcasals@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (145, 'Cristina de Huguet', 64, 'Femenino', 'Oriente', '2025-04-18', 'pizarrorosa-maria@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (146, 'Delfina Arnal Benítez', 60, 'Femenino', 'Paracentral', '2024-07-22', 'cisnerosfelisa@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (147, 'Tadeo Castells Mendez', 43, 'Masculino', 'Oriente', '2024-03-20', 'linacastrillo@valderrama.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (148, 'Gastón Alberdi Leon', 30, 'Masculino', 'Paracentral', '2021-06-20', 'haroldocozar@mercader-esteban.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (149, 'Juanito Parra Otero', 61, 'Masculino', 'Occidente', '2020-07-25', 'omillan@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (150, 'Bartolomé Marquez Becerra', 43, 'Masculino', 'Centro', '2022-04-10', 'pujoljose-angel@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (151, 'Coral Barrios Giménez', 36, 'Masculino', 'Occidente', '2024-11-01', 'proura@carreno.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (152, 'Ale Remedios Serrano Falcón', 68, 'Masculino', 'Oriente', '2020-10-30', 'ocalatayud@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (153, 'Borja Macías Duque', 46, 'Femenino', 'Paracentral', '2020-08-09', 'priscilamari@posada.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (154, 'Tamara Cañizares Goñi', 50, 'Femenino', 'Paracentral', '2024-01-10', 'demetrio48@falcon.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (155, 'Abril Montero Huertas', 60, 'Masculino', 'Centro', '2022-08-23', 'itziar30@vizcaino.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (156, 'Américo Zabaleta Frutos', 50, 'Masculino', 'Oriente', '2020-06-29', 'ijorda@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (157, 'Jose Miguel Sierra Verdú', 70, 'Masculino', 'Occidente', '2025-05-31', 'xavier25@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (158, 'Desiderio Hierro Galvez', 32, 'Masculino', 'Occidente', '2021-07-16', 'curroguillen@ballester-fonseca.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (159, 'Eliana del Andrade', 19, 'Femenino', 'Centro', '2023-01-22', 'graciana78@frias-bustamante.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (160, 'Arturo Sanz Arellano', 48, 'Masculino', 'Centro', '2024-07-31', 'riquelmeanacleto@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (161, 'Susana Gibert-Céspedes', 44, 'Femenino', 'Occidente', '2024-11-12', 'angeles02@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (162, 'Rosario Grande Almagro', 49, 'Masculino', 'Paracentral', '2021-05-21', 'bolanosfortunato@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (163, 'Guadalupe Rocha', 27, 'Masculino', 'Centro', '2021-06-02', 'xvalencia@cisneros-carreras.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (164, 'Rosalina Almansa', 67, 'Femenino', 'Paracentral', '2021-08-14', 'msegovia@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (165, 'Victor Manuel Benavides Gallo', 29, 'Masculino', 'Paracentral', '2024-03-03', 'fermindominguez@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (166, 'Clemente Barceló Ferrero', 53, 'Masculino', 'Occidente', '2021-05-06', 'cecilia70@luz.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (167, 'Fulgencio Amo Luz', 47, 'Masculino', 'Occidente', '2022-04-20', 'quesadamaxima@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (168, 'Jimena del Pombo', 60, 'Femenino', 'Oriente', '2020-12-05', 'lina94@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (169, 'Almudena Cayetana Andres Bermúdez', 57, 'Femenino', 'Paracentral', '2023-01-17', 'zuribe@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (170, 'Osvaldo Narváez Fonseca', 28, 'Masculino', 'Paracentral', '2022-02-01', 'carballodionisio@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (171, 'Calisto Beltran Arroyo', 34, 'Masculino', 'Occidente', '2021-01-05', 'barriosbaldomero@feijoo.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (172, 'Asdrubal Arnau Aller', 67, 'Masculino', 'Paracentral', '2021-06-28', 'quirogacosme@pomares.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (173, 'Olalla Guijarro Diaz', 35, 'Femenino', 'Paracentral', '2021-01-06', 'urbanomayoral@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (174, 'Águeda Valero Larrañaga', 63, 'Femenino', 'Oriente', '2020-12-22', 'felipe97@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (175, 'Cecilio Rubio Cabañas', 35, 'Masculino', 'Oriente', '2024-03-23', 'cristobal81@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (176, 'Marisol Valenzuela-Chaves', 52, 'Masculino', 'Centro', '2021-09-26', 'ainoa87@santamaria.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (177, 'Oriana Prats Cortes', 27, 'Femenino', 'Occidente', '2022-08-01', 'ecorominas@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (178, 'Iris Pedrero', 62, 'Masculino', 'Occidente', '2021-01-22', 'eladioroura@bueno-vazquez.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (179, 'Ciríaco León', 22, 'Masculino', 'Paracentral', '2024-07-30', 'carlosiriarte@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (180, 'Fátima Dalmau-Cabo', 39, 'Femenino', 'Paracentral', '2023-03-06', 'rromero@cueto.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (181, 'Camilo Terrón', 21, 'Masculino', 'Occidente', '2023-04-29', 'qcanete@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (182, 'Manola Seco-Mendizábal', 42, 'Femenino', 'Centro', '2022-11-01', 'josue48@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (183, 'Alba Tejera Alarcón', 48, 'Femenino', 'Centro', '2022-11-24', 'cguardiola@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (184, 'Camila Corominas Malo', 37, 'Femenino', 'Paracentral', '2022-08-16', 'roldanricardo@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (185, 'Aurora de Checa', 52, 'Femenino', 'Occidente', '2024-10-29', 'cpalacio@morell-manrique.net');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (186, 'Domitila Cadenas Sastre', 32, 'Femenino', 'Oriente', '2024-02-04', 'fanny76@carrera.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (187, 'Noa Jara Morera', 49, 'Femenino', 'Centro', '2024-10-12', 'yroldan@villalonga-ferrandiz.org');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (188, 'Custodia del Parra', 39, 'Femenino', 'Paracentral', '2023-01-23', 'ayusograciana@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (189, 'Adela Benítez Gaya', 47, 'Femenino', 'Occidente', '2025-02-16', 'socorro67@fuertes.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (190, 'Natividad Selena Romero Anglada', 43, 'Masculino', 'Centro', '2024-02-22', 'torrejose-ignacio@hotmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (191, 'Cristina Tomé Llanos', 59, 'Femenino', 'Paracentral', '2024-04-27', 'lupe77@gmail.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (192, 'Prudencio Planas Uriarte', 47, 'Masculino', 'Occidente', '2020-07-14', 'vinicioaroca@losada.net');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (193, 'Lupe Alegre Sierra', 34, 'Masculino', 'Paracentral', '2022-08-07', 'urio@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (194, 'Flavio Néstor Diez Palomar', 31, 'Masculino', 'Paracentral', '2021-02-12', 'piedad55@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (195, 'Dionisia Prat Amor', 39, 'Femenino', 'Paracentral', '2020-10-11', 'emarti@figueras.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (196, 'Juan Luis Cabello Valdés', 66, 'Masculino', 'Paracentral', '2023-05-31', 'rosalinda02@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (197, 'Concepción de Gallego', 23, 'Masculino', 'Paracentral', '2023-12-08', 'albinopoza@yahoo.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (198, 'Magdalena Iñiguez Valls', 65, 'Femenino', 'Centro', '2021-09-02', 'alicia52@ayala.com');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (199, 'Rosendo Chacón Guillén', 32, 'Masculino', 'Centro', '2020-09-25', 'valentinrios@aguila-espanol.es');
INSERT INTO Cliente (id_cliente, nombre, edad, genero, region, fecha_registro, correo_electronico) VALUES (200, 'Alicia Reig Agullo', 66, 'Femenino', 'Centro', '2023-11-12', 'wcalvo@gmail.com');